### ISSUE TITLE
css width jump by real element width ?

### ISSUE THREAD

**Issue by dascritch** [dascritch/ondemiroir-audio-tag#5]

**Comment by dascritch** [comment]
Or parameterizable, as injected CSS go thru our template interpretor ?

**Comment by yoanmalie** [comment]
@dascritch I saw this project via one of your recent Tweet. Maybe i can help but can i have more details on this issue ?

**Comment by dascritch** [comment]
Hello and thanks !
I've concevied my player as a polyfill for a later version with WebComponents. You can try it at <http://cpu.pm>
It has 2 rendering mode : larger than 640px width and smaller, cf https://github.com/dascritch/ondemiroir-audio-tag/blob/master/src/ondeplayer.css.js#L213 
But this is not optimal, as everything can change in which layout/space my player will appear.

I can replace this rule in javascript, watching any resize/orientation/whatever event, but sincerely, i think it would be very ugly.
Maybe there is a better way to change this out of the *max-width* of the body, but on the allowed space allocated to the player.

But i don't know it.

If you want to try it, you will need google closure, and run `./make.sh` (yes, I know, nodejs is may be better...)

**Comment by dascritch** [comment]
Well, there is a CSS Element Query specification, and it seems there is a not so bad polyfill
http://elementqueries.com/
I'll have to simplify it, and as we already have the css definitions in string, I can remove a lot of code

**Comment by dascritch** [comment]
Yes, I can now use css variables, as phracking Safari seems nearly to understand it.

**Comment by dascritch** [comment]
Done in webcomponent version
